name: wo_form_service
description: "An implementation of services from wo_form."
version: 1.0.0
repository: https://github.com/BudgetChess/wo_form_service
funding:
  - https://ko-fi.com/chresyr

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  http: ^1.2.2
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  path_provider: ^2.1.5
  wo_form: ^1.3.0

# dependency_overrides:
#   wo_form:
#     path: ../wo_form

dev_dependencies:
  very_good_analysis: ^6.0.0

flutter:
